SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, 
ROUND(AVG(B.REVIEW_SCORE), 2) as SCORE
FROM REST_INFO as A
JOIN REST_REVIEW as B
ON A.REST_ID = B.REST_ID
GROUP BY REST_ID
HAVING ADDRESS LIKE '서울%' AND count(*) >= 2
ORDER BY SCORE DESC, A.FAVORITES DESC