SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, 
DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_REPLY as B
INNER JOIN USED_GOODS_BOARD as A
ON B.BOARD_ID = A.BOARD_ID
WHERE A.CREATED_DATE like '2022-10%'
ORDER BY B.CREATED_DATE ASC, A.TITLE ASC